version: '4'

services:
  psql:
    image: postgres:16
    container_name: psql
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


  integracao:
    container_name: integracao
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - psql