# Generated by Django 5.0.4 on 2024-04-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('andamento', models.BooleanField(default=False)),
                ('chave', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_chamado', models.CharField(help_text='ex: 0923-000052', max_length=11)),
                ('nome_grupo', models.CharField(blank=True, max_length=256, null=True)),
                ('nome_categoria', models.CharField(blank=True, max_length=256, null=True)),
                ('assunto', models.CharField(blank=True, max_length=512, null=True)),
                ('data_criacao', models.DateField()),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('nome_operador', models.CharField(blank=True, max_length=128, null=True)),
                ('nome_status', models.CharField(blank=True, max_length=128, null=True)),
                ('possui_sla', models.CharField(blank=True, help_text='ex: N ou S', max_length=1, null=True)),
                ('nome_sla_status_atual', models.CharField(blank=True, max_length=128, null=True)),
                ('first_call', models.CharField(blank=True, help_text='ex: N ou S', max_length=1, null=True)),
                ('sla_1_expirado', models.CharField(blank=True, max_length=128, null=True)),
                ('sla_2_expirado', models.CharField(blank=True, max_length=128, null=True)),
                ('total_horas_1_atendimento', models.FloatField(blank=True, editable=False, null=True)),
                ('total_horas_1_2_atendimento', models.FloatField(blank=True, editable=False, null=True)),
                ('tempo_restante_1', models.FloatField(blank=True, editable=False, null=True)),
                ('tempo_restante_2', models.FloatField(blank=True, editable=False, null=True)),
                ('nome_sistema', models.CharField(blank=True, max_length=128, null=True)),
                ('qnt_interacao', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('chave', models.IntegerField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField()),
                ('seguencia', models.IntegerField()),
                ('status_acao_nome_relatorio', models.CharField(max_length=128)),
                ('fantasia_fornecedor', models.CharField(blank=True, max_length=128, null=True)),
                ('chamado_aprovadores', models.CharField(blank=True, max_length=1024, null=True)),
                ('tempo_corrido_interacao', models.FloatField(blank=True, editable=False, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.chamado')),
            ],
            options={
                'verbose_name_plural': 'Interações',
            },
        ),
    ]
