# Generated by Django 5.0.4 on 2024-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='chamado_aprovadores',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
