# Generated by Django 5.0.4 on 2024-04-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestorExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('setor', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Gestores Expense',
            },
        ),
        migrations.CreateModel(
            name='Notificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('grupo', models.IntegerField()),
                ('operacao', models.CharField(max_length=128)),
                ('token_bot', models.CharField(max_length=256)),
                ('ativo', models.BooleanField(default=False)),
                ('gestor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacao_expenses.gestorexpense')),
            ],
        ),
        migrations.CreateModel(
            name='UserVexpenses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('operacao', models.CharField(blank=True, max_length=128, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('gestor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacao_expenses.gestorexpense')),
            ],
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avulso', models.IntegerField()),
                ('aberto', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacao_expenses.uservexpenses')),
            ],
        ),
    ]
