# Generated by Django 5.0.4 on 2024-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao_expenses', '0002_alter_notificar_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognotificacao',
            name='grupo',
            field=models.BigIntegerField(),
        ),
    ]
