# Generated by Django 5.0.4 on 2024-05-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorOs',
            fields=[
                ('os', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=128)),
                ('operador', models.CharField(max_length=128)),
                ('detalhe', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='TecnicoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tecnico', models.CharField(max_length=128)),
                ('chat_id', models.BigIntegerField()),
                ('mensagem', models.TextField()),
                ('sla', models.IntegerField()),
                ('cod_os', models.IntegerField()),
                ('data_envio', models.DateTimeField(auto_now=True)),
                ('envio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='TempoSla',
            fields=[
                ('sla', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'S.L.A.',
            },
        ),
        migrations.CreateModel(
            name='TipoOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('sla', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo O.S.',
            },
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('mk', models.IntegerField()),
                ('nome', models.CharField(max_length=256)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InformacaoOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('id_tipo_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ost.tipoos')),
            ],
            options={
                'verbose_name_plural': 'Informacões O.S.',
            },
        ),
    ]
